name: "\U0001F41B Bug Report"
description: "When something isn't working as expected or documented"
labels: ["kind/bug"]
assignees:
  - freehere107

body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening an issue. Please note that we try to keep the
        issue tracker reserved for bug reports and feature requests.
        For general usage questions, contact hello@subscan.io.

  - type: checkboxes
    attributes:
      label: Confirmation
      description: Please make sure to have followed the following checks.
      options:
        - label: My issue isn't already found on the issue tracker.
          required: true
        - label: I have read the Subscan API documentation (if it's an API bug).
          required: true

  - type: textarea
    attributes:
      label: Affected network(s)
      description: |
        Please list the networks as a list, for example:
        - Kusama
        - Polkadot
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        How can your issue be replicated?
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected output
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual output
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional factoids or references
      description: Is there any other important information you'd like to share?
    validations:
      required: false
