blank_issues_enabled: true
contact_links:
  - name: Subscan Service Status
    url: https://subscan.statuspage.io/
    about: The real-time service status, incidents, and scheduled maintenances of Subscan.io

  - name: Subscan API Documentation
    url: https://docs.api.subscan.io/
    about: The Open API documentation of Subscan.io
