name: "\u2728 Feature Request"
description: "Suggest a new feature or other enhancement"
labels: ["kind/enhancement"]
assignees:
  - freehere107
  - yakio

body:
  - type: markdown
    attributes:
      value: >
        Thank you for opening an issue. Please note that we try to keep the
        issue tracker reserved for bug reports and feature requests.
        For general usage questions, contact hello@subscan.io.

  - type: input
    attributes:
      label: Network(s)
      placeholder: e.g., Polkadot, Kusama, ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Provide a quick overview of the proposed change.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use cases
      description: >
        In order to properly evaluate a feature request, it is necessary to understand
        the use-cases for it. Please describe below the **end goal** you are trying
        to achieve that has led you to request this feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional factoids or references
      description: |
        Is there any other important information you'd like to share?
    validations:
      required: false
