name: "\U0001F680 Runtime Update"
description: Submit the necessary information for network runtime update
labels:
  - kind/runtime-update
assignees:
  - freehere107
  - yakio

body:
  - type: markdown
    attributes:
      value: >
        Thank you for opening an issue. Please note that we try to keep the
        issue tracker reserved for bug reports and feature requests. For general
        usage questions, contact hello@subscan.io.

  - type: dropdown
    attributes:
      label: Your identity
      options:
        - Project developer
        - Community user
    validations:
      required: true

  - type: input
    attributes:
      label: Network(s)
      placeholder: e.g., Polkadot, Kusama, ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Runtime update description
      description: |
        Describe the estimated time and updated detail about the new version.

        Can add some important events to batch & staking to ensure ease of analysis. For users tracking events this could be a breaking change, here is a tl;dr:

        - `EraPayout` => `EraPaid`
        - `Reward` => `Rewarded`
        - `Slash` => `Slashed`
        - `StakingElection` => `StakersElected`
      placeholder: |
        1. Current version:
        2. The latest version:
        3. Estimated time:
        4. Version update content:
    validations:
      required: true

  - type: textarea
    attributes:
      label: The JSON file of custom types
      description: >
        (Optional) If you have the updated types JSON file, provide the URL or paste it into a code block.
    validations:
      required: false
